### ISSUE TITLE
point d'exclamation blanc

### ISSUE THREAD

**Issue by Aniki140** [FallenMax/mithril-emmet#8]
probleme avec le raccourcis du doctype (!)

**Comment by FallenMax** [comment]
@Aniki140  Hi, looks like you are using vscode built-in feature instead of this extension.

Emmet is a built-in feature of vscode. This extension is created to allow abbreviation expansion for "hyperscript syntax" like `h('span', 'text')` or `m('span', 'text')` . So if you are not using or aware of these, you can safely uninstall this extension as it's not required.
