### ISSUE TITLE
Missing doc type before html tag

### ISSUE THREAD

**Issue by A7bert** [FallenMax/mithril-emmet#9]
very minor issue

`<!DOCTYPE html>` is missing when use doc emmet abbreviation.

Would be good to include for linting reason, thanks!

**Comment by FallenMax** [comment]
@A7bert  Hi, looks like you are using vscode built-in feature instead of this extension.

Emmet is a built-in feature of vscode. This extension is created to allow abbreviation expansion for "hyperscript syntax" like `h('span', 'text')` or `m('span', 'text')` . So if you are not using or aware of these, you can safely uninstall this extension as it's not required.
